modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="sololevelingcore"
version="1.0.0"
displayName="Solo Leveling Core"
description='''
Mod Solo Leveling, système de base (level, XP).
'''
authors="Egoshix"
